SELECT ?player ?club ?apps ?start ?end WHERE {
  VALUES ?club { {{VALUES}} }
  ?player p:P54 ?stmt .
  ?stmt ps:P54 ?club ;
        pq:P580 ?start ;
        pq:P1350 ?apps .
  OPTIONAL { ?stmt pq:P582 ?end . }
  FILTER( !BOUND(?end) || YEAR(?end) >= 1999 )
  FILTER EXISTS { ?player wdt:P27 [] }
  FILTER EXISTS { ?player wdt:P413 [] }
}
